#!/bin/bash -e




function relUp {
  cp -f env-default .env
  sed -i "s#CASSANDRA_DATA_DIR_VAR#${PWD}/data/cassandra#" .env
  sed -i "s#POSTGRES_DATA_DIR_VAR#${PWD}/data/cassandra#" .env
  sed -i "s#HSQLDB_DATA_DIR_VAR#${PWD}/data/hsqldb#" .env
  docker-compose up -d tb
}

function stop {
  docker-compose stop
}

function down {
  docker-compose down -v
}

case "$1" in
# Start development 
run)
  relUp $2
  ;;  
stop)
  stop
  ;;
down)
  down
  ;;
*)
  echo "usage: mima run|stop|down|backup|web"
  ;;
esac
